Repository emberjs/rfcs, pull requests merged in 2018-10, with the labels that each got.

#370 Deprecate `computed().volatile()`
  text/0000-deprecate-computed-volatile.md
Labels: Final Comment Period

#372 [RFC ember-data] modelFactoryFor
  text/0000-ember-data-model-factory-for.md
Labels: Final Comment Period, T-ember-data

#369 Deprecate Computed Overridability and `.readOnly()`
  text/0000-deprecate-computed-clobberability.md
Labels: Final Comment Period, T-framework

#375 Deprecate Computed `.property()` Modifier
  text/0000-deprecate-computed-property-modifier.md
Labels: Final Comment Period, T-framework
