Repository emberjs/rfcs, pull requests merged in 2018-11, with the labels that each got.

#364 RFC: Ember 2018 Roadmap
  text/0000-roadmap-2018.md
Labels: Final Comment Period

#392 Deprecate setupComponentManager String Lookup
  text/0000-deprecate-component-manager-string-lookup.md
Labels: Final Comment Period, T-components, T-deprecation, T-framework

#391 Router Helpers
  text/0000-router-helpers.md
Labels: Final Comment Period, T-framework, T-routing

#398 RouteInfo Metadata
  text/0000-RouteInfo-Metadata.md
Labels: Final Comment Period

#300 RFC Process Update
  text/0300-rfc-process-update.md
Labels: Final Comment Period
