Repository emberjs/rfcs, pull requests merged in 2019-06, with the labels that each got.

#491 Deprecate disconnectOutlet
  text/0491-deprecate-disconnect-outlet.md
Labels: Final Comment Period

#494 Async Observers
  text/0494-async-observers.md
Labels: Final Comment Period

#452 [Data] Medium Term Plan
  text/0452-ember-data-medium-term-plan.md
Labels: Final Comment Period, T-ember-data

#461 [DATA] Singleton RecordData
  text/0461-ember-data-singleton-record-data.md
Labels: Final Comment Period, T-deprecation, T-ember-data

#487 Custom Model Classes
  text/0487-custom-model-classes.md
Labels: Final Comment Period, T-ember-data
