Repository emberjs/rfcs, pull requests merged in 2019-08, with the labels that each got.

#466 Request state service
  text/0466-request-state-service.md
Labels: Final Comment Period, T-ember-data

#522 RFC - deprecate default serializers and adapters
  text/0000-default-serializers-and-adapters.md
Labels: Final Comment Period, T-deprecation, T-ember-data

#521 [DATA] findRecord/peekRecord via Identifier
  text/0521-find-by-identifier.md
Labels: Final Comment Period, T-deprecation, T-ember-data

#523 @model for route templates
  text/0523-model-argument-for-route-templates.md
Labels: Final Comment Period, T-routing, T-templates
