Repository emberjs/rfcs, pull requests merged in 2019-04, with the labels that each got.

#403 [DATA] Identifiers
  text/0403-ember-data-identifiers.md
Labels: Final Comment Period, T-ember-data

#425 Website Redesign RFC
  images/EmberJS_Homepage_Outline.pdf
  images/survey_results.png
  images/survey_results_analysis.pdf
  images/website_1.png
  images/website_2_header_dropdown.png
  images/website_3_url_examples.png
  images/website_4-button_ui.png
  images/website_5_scrolled_nav.png
  images/website_6_nav_alt.png
  images/website_7_pointer.png
  text/0425-website-redesign.md
Labels: Final Comment Period, T-infrastructure, T-learning, T-steering

#389 Dynamic tags in glimmer templates
  text/0389-dynamic-tag-names.md
Labels: Final Comment Period, T-framework, T-templates

#451 Injection Parameter Normalization
  text/0451-injection-parameter-normalization.md
Labels: Final Comment Period, T-framework

#470 `{{fn}}` Helper
  text/0470-fn-helper.md
Labels: Final Comment Period, T-templates

#471 `{{on}}` Modifier
  text/0471-on-modifier.md
Labels: Final Comment Period, T-framework, T-templates

#460 Yieldable named blocks
  text/0460-yieldable-named-blocks.md
Labels: Final Comment Period, T-framework, T-templates
