Repository emberjs/rfcs, pull requests merged in 2019-03, with the labels that each got.

#446 Contribution Guides
  text/0446-contribution-guides.md
Labels: Final Comment Period, T-infrastructure, T-learning

#440 Decorator Support RFC
  text/0440-decorator-support.md
Labels: Final Comment Period, T-framework

#457 Nested Invocations in Angle Bracket Syntax
  images/457-autocomplete-problem.gif
  images/457-dasherization.jpg
  images/457-when-to-use-curlies.jpg
  text/0457-nested-lookups.md
Labels: Final Comment Period, Octane

#459 Angle Bracket Invocations For Built-in Components
  text/0459-angle-bracket-built-in-components.md
Labels: Final Comment Period, Octane, T-components, T-framework, T-templates

#449 Deprecate {{partial}}
  text/0000-template.md
Labels: Final Comment Period, T-framework, T-templates

#445 Deprecate {{with}}
  text/0445-deprecate-with.md
Labels: Final Comment Period, T-framework, T-templates
