Repository emberjs/rfcs, pull requests merged in 2019-01, with the labels that each got.

#386 Remove jQuery by default
  text/0386-remove-jquery.md
Labels: Final Comment Period, T-framework

#408 Decorators
  text/0000-decorators.md
Labels: Final Comment Period, Octane, T-framework

#272 Deprecate Function.prototype.on, Function.prototype.property, Function.prototype.observes
  text/000-deprecation-native-function-prototype-extensions.md
Labels: Final Comment Period, T-deprecation, T-framework

#395 @ember-data packages
  text/0000-ember-data-packages.md
Labels: Final Comment Period, T-ember-data

#416 Glimmer Components
  text/0000-glimmer-components.md
Labels: Final Comment Period, Octane, T-framework

#435 Forwarding Element Modifiers with "Splattributes"
  text/0000-modifier-splattributes.md
Labels: Final Comment Period
