Repository emberjs/rfcs, pull requests merged in 2020-04, with the labels that each got.

#580 Destroyables
  text/0580-destroyables.md
Labels: Final Comment Period, T-framework

#496 Strict mode templates
  text/0496-handlebars-strict-mode.md
Labels: Final Comment Period, T-templates

#477 Blueprints Update
  text/0477-blueprints-update.md
Labels: Final Comment Period
