Repository emberjs/rfcs, pull requests merged in 2020-05, with the labels that each got.

#519 Ember 2020 Roadmap RFC
  text/0519-2019-2020-roadmap.md
Labels: Final Comment Period, T-steering

#615 Autotracking Memoization
  text/0615-autotracking-memoization.md
Labels: Final Comment Period

#507 v2 Addon Format (Embroider compatibility)
  text/0000-embroider-v2-package-format.md
Labels: Final Comment Period

#625 Helper Managers
  text/0625-helper-managers.md
Labels: Final Comment Period, T-framework, T-templates
