Repository emberjs/rfcs, pull requests merged in 2021-01, with the labels that each got.

#680 Deprecate Implicit Injection on arbitrary Ember Framework objects
  text/0680-implicit-injection-deprecation.md
Labels: Final Comment Period, T-deprecation, T-framework

#700 Clarify and amend import paths in RFC #496 and #671
  text/0496-handlebars-strict-mode.md
  text/0671-modernize-built-in-components-1.md
Labels: T-components, T-framework, T-templates

#698 Deprecate `<LinkTo>` Component Positional Arguments
  text/0698-deprecate-link-to-positional-arguments.md
Labels: Final Comment Period, T-components, T-framework

#692 Deprecate Array Observers
  text/0692-deprecate-array-observers.md
Labels: Final Comment Period

#691 Deprecate passing `classBinding` and `classNameBindings` as arguments
  text/0691-deprecate-class-binding-and-class-name-bindings.md
Labels: Final Comment Period

#690 Deprecate `{{attrs}}` in templates
  text/0690-deprecate-attrs-in-templates.md
Labels: Final Comment Period

#562 Adding Logical Operators to Templates
  text/0000-add-logical-operators.md
Labels: Final Comment Period

#707 Modernize built-in components (part 2)
  text/0707-modernize-built-in-components-2.md
Labels: Final Comment Period, T-components, T-framework, T-templates

#706 Deprecate the Ember Global
  text/0706-deprecate-ember-global.md
Labels: Final Comment Period, T-framework

#705 Deprecate jQuery Integration Optional Feature
  text/0705-deprecate-jquery-optional-feature.md
Labels: Final Comment Period, T-deprecation, T-framework

#704 Deprecate Octane Optional Features
  text/0704-deprecate-octane-optional-features.md
Labels: Final Comment Period, T-deprecation, T-framework

#689 Deprecate {{hasBlock}} and {{hasBlockParams}} in templates
  text/0689-deprecate-has-block.md
Labels: Final Comment Period, T-framework, T-templates

#560 Adding Equality Operators to Templates
  text/0000-add-equality-operators.md
Labels: Final Comment Period
