Repository emberjs/rfcs, pull requests merged in 2021-02, with the labels that each got.

#561 Adding Numeric Comparison Operators to Templates
  text/0561-add-numeric-comparison-operators.md
Labels: Final Comment Period

#669 Tracked Storage Primitives
  text/0669-tracked-storage-primitive.md
Labels: Final Comment Period

#711 Deprecate Auto Location
  text/0711-deprecate-auto-location.md
Labels: Final Comment Period, T-framework, T-routing

#702 Add eslint-plugin-qunit to ember-cli blueprint
  text/0702-eslint-plugin-qunit.md
Labels: Final Comment Period, T-ember-cli, T-testing

#566 @cached
  text/0566-memo-decorator.md
Labels: Final Comment Period, T-framework
