Repository emberjs/rfcs, pull requests merged in 2022-07, with the labels that each got.

#334 Deprecate Ember Utils
  text/0334-deprecate-ember-utils.md
Labels: Needs Champion, Final Comment Period, T-deprecation, T-framework

#793 EmberData | Polymorphic Relationship Support
  text/0793-polymporphic-relations-without-inheritance.md
Labels: T-ember-data, Final Comment Period

#741 rfc: ember-data | Deprecate Accessing Static Fields On Model Prior To Lookup
  text/0741-ember-data-deprecate-model-static-field-access-without-lookup.md
Labels: T-ember-data, Final Comment Period, T-deprecation

#740 rfc: ember-data | deprecate-non-strict-types
  text/0740-ember-data-deprecate-non-strict-relationships.md
Labels: T-ember-data, Final Comment Period, T-deprecation

#821 RFC: public types for Owner, Transition, RouteInfo
  text/0821-public-types.md
Labels: Final Comment Period, T-framework, T-learning, T-TypeScript
