Repository emberjs/rfcs, pull requests merged in 2022-03, with the labels that each got.

#779 First-Class Component Templates
  text/0779-first-class-component-templates.md
Labels: Final Comment Period, T-templates, T-framework

#724 RFC: Official TypeScript support
  text/0724-road-to-typescript.md
Labels: Final Comment Period, T-infrastructure, T-Tooling

#795 ember-data: Return a Promise from Model.save()
  text/0795-ember-data-return-promise-save.md
Labels: T-ember-data, Final Comment Period

#786 rfc: Ember Learn | Add Ember cookbook
  text/0786-ember-cookbook.md
Labels: T-learning

#801 Deprecate `blacklist` and `whitelist` build options
  text/0801-deprecate-blacklist-and-whitelist-build-options.md
Labels: Final Comment Period, T-deprecation, T-ember-cli

#748 RFC: Glimmer component `Signature` type
  text/0748-glimmer-component-signature.md
Labels: Final Comment Period, T-framework
