Repository emberjs/rfcs, pull requests merged in 2022-09, with the labels that each got.

#830 RFC: Evolving Ember's Major Version Process
  text/0830-evolving-embers-major-version-process.md
Labels: Final Comment Period, T-framework, T-learning, T-steering

#847 Deprecate support for `ember-cli-qunit` and `ember-cli-mocha` when generating test blueprints
  text/0847-deprecate-support-for-ember-cli-qunit-and-ember-cli-mocha-when-generating-test-blueprints.md
Labels: T-ember-data, Final Comment Period, T-deprecation, T-framework, T-ember-cli

#849 data: updates to the polymorphic relationships rfc
  text/0793-polymporphic-relations-without-inheritance.md
Labels: T-ember-data, Final Comment Period

#848 RFC: Deprecate array prototype extensions
  text/0848-deprecate-array-prototype-extensions.md
Labels: Final Comment Period, T-deprecation, T-framework, T-ember-cli, S-Exploring
