Repository emberjs/rfcs, pull requests merged in 2023-09, with the labels that each got.

#918 Deprecate Support for Travis CI
  text/0918-deprecate-travis-ci-support.md
Labels: Final Comment Period, T-learning, T-ember-cli, S-Exploring

#902 Revise RFC 0800 with learnings from implementation
  text/0800-ts-adoption-plan.md
Labels: T-ember-cli, T-TypeScript, E-Polaris

#831 Standardize use of scripts in package.json for common tasks
  images/ember_test.png
  images/npm_test.png
  text/0831-standardize-use-npm-yarn.md
Labels: Final Comment Period, T-learning, T-ember-cli, S-Exploring

#961 Bugfix - date format on RFC 831
  text/0831-standardize-use-npm-yarn.md
Labels: bug
