Repository emberjs/rfcs, pull requests merged in 2025-03, with the labels that each got.

#1078 Fix title comment
  0000-template.md
Labels: bug

#1068 tracked-built-ins built-in
  text/1068-tracked-collections.md
Labels: Final Comment Period, S-Exploring

#964 EmberData | deprecate legacy finder support
  text/0964-deprecate-legacy-request-support.md
Labels: T-ember-data, Final Comment Period, T-learning, S-Exploring
